  language: python
  python:
    - 3.6
  install:
    - pip install pytest pytest-cov
    - pip install coveralls
    - pip install readline
    - pip install colored
  script:
    - pytest
  after_success:
    - coveralls
